POST http://localhost:8888/auth
Content-Type: application/json

{
  "email": "new@vigi.com",
  "password": "password"
}

###

POST http://localhost:8888/auth/register
Content-Type: application/json

{
  "email": "heyheyhey@hey.com",
  "password": "password"
}

###

GET http://localhost:8888/api/people
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTUxYzBhNjEwN2RjMjFhYjI0OTQxOTcifQ.K36U9kR6VV9Vag9g6IcmuwpeA7Zow-q-eOXOXj9ARQU