GET http://localhost:8888/api/movies

###

GET http://localhost:8888/api/movies/594f7ec49sdhfkfsddsdswhjfhdskjh9e00c7385daeb4c

###

POST http://localhost:8888/api/movies
Content-Type: application/json

{

}

###

PATCH http://localhost:8888/api/movies/594f736b6dca7e6fc3b05318
Content-Type: application/json

{
  "cast": [{
    "person": "5952563ab8d0af502d90eed0",
    "role": "Lead actor"
  }]
}

###

DELETE http://localhost:8888/api/movies/594f736bd8ca7e86fc3b05319